apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: gordon
  region: eu-west-1
  version: "1.18"

nodeGroups:
  - name: spot-nodes
    labels: { role: spots }
    minSize: 2
    maxSize: 3
    instancesDistribution:
        maxPrice: 0.030
        instanceTypes: ["t3.large"] # At least one instance type should be specified
        onDemandBaseCapacity: 0
        onDemandPercentageAboveBaseCapacity: 50
        spotInstancePools: 1
    volumeSize: 50
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_rsa.pub
    tags:
      nodegroup-role: worker

# Enable logging
cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]